server:
  port: 8080
  timeout: 30s
  debug: true

database:
  host: localhost
  port: 5432
  user: postgres
  password: password123
  dbname: testordentdb
  sslmode: disable
  max_open_conns: 20
  max_idle_conns: 5
  conn_max_lifetime: 1h

auth:
  jwt_secret: "super-secure-jwt-secret-key-123"
  token_expiry: 24h

cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
